[package]
name = "rim"
version = "0.1.1"
edition = "2021"
authors = ["Gábor Csárdi <csardi.gabor@gmail.com"]
license = "MIT"
description = "Manage R installations"
readme = "README.md"
homepage = "https://github.com/gaborcsardi/rim"
repository = "https://github.com/gaborcsardi/rim"
keywords = ["R", "cli"]
categories = ["command-line-utilities"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
futures = "0.3.17"
futures-util = "0.3.14"
lazy_static = "1.3.0"
nix = "0.23.0"
regex = "1.5.4"
reqwest = { version = "0.11", features = ["json", "stream"] }
semver = "1.0.4"
serde_json = "1.0.69"
shellexpand = "2.1.0"
tokio = { version = "1", features = ["full"] }
