name: Build rig containers for new release

on:
  workflow_dispatch:
    inputs:
      inpconts:
        description: |
          Containers, comma separated list or 'all'.
        required: false
        default: 'devel'
        type: string
  schedule:
    - cron:  '55 7 * * *'

jobs:

  # ------------------------------------------------------------------------

  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      containers: ${{steps.setup-matrix.outputs.containers}}

    steps:
    - uses: actions/checkout@v4
    - name: Set up matrix of containers
      id: setup-matrix
      run: |
        cs=$(python containers/matrix.py ${{ github.event.inputs.inpconts || 'devel' }})
        echo "containers=`jq -c <containers/matrix.json`" >> $GITHUB_OUTPUT

  # ------------------------------------------------------------------------

  containers:
    needs: setup-matrix
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.setup-matrix.outputs.containers) }}
    runs-on: ubuntu-latest
    name: ${{ matrix.config.name }}

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm64
        provenance: false
        context: containers/${{ matrix.config.dir }}
        build-args: "${{ join(matrix.config.args, '\n') }}"
        push: true
        outputs:
        tags: "${{ join(matrix.config.tags, '\n') }}"
