
name: Debian repo

on:
  workflow_dispatch:

jobs:
  deploy-repo:
    name: Update Debian Repo
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Update
      uses: gaborcsardi/debian-repo@v1
