
name: Debian repo

on:
  workflow_dispatch:

jobs:
  deploy-repo:
    name: Update Debian Repo
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Update
      uses: gaborcsardi/debian-repo@v1
      with:
        gpg-public-key: ${{ secrets.PUBLIC_REPO_KEY }}
        gpg-private-key: ${{ secrets.PRIVATE_REPO_KEY }}
        gpg-passphrase: ${{ secrets.REPO_KEY_PASSPHRASE }}
