
name: Test

on:
  workflow_dispatch:
  push:
    branches: [ 'dev', 'main' ]
  schedule:
  - cron: '30 6 * * *'

jobs:

  linux:
    runs-on: ubuntu-18.04
    name: Linux

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true

    - name: Build rim
      run: |
        docker build -o out .

    - name: debug
      run: |
        ls -l

    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: rim-linux
        path: 'rim-*.tar.gz'


  macos:
    runs-on: macos-11
    if: false
    name: macOS

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Install rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rust.sh
        sh rust.sh -y

    - name: Build rim
      run: |
        make macos-unsigned-x86_64

    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: rim-macos
        path: 'rim-*.pkg'


  windows:
    runs-on: windows-latest
    if: false
    name: Windows

    steps:

    - name: find
      run: |
        find --help
      shell: bash

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install make
      run: choco install make

    - name: Install curl
      run: choco install curl

    - run: |
        make win
      shell: bash

    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: rim-windows
        path: 'rim-*.exe'
