
name: Test

on:
  workflow_dispatch:
  push:
    branches: [ 'dev', 'main' ]
  schedule:
  - cron: '30 6 * * *'

jobs:

  linux:
    runs-on: ubuntu-18.04
    name: Linux
    env:
      RUST_BACKTRACE: 1

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Build rim
      run: |
        docker build -t rim:latest .
        docker run --name quickrim rim:latest ls out
        docker cp quickrim:out .
        ls out
        cp out/rim* .

    - name: Upload build as artifact
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: rim-linux
        path: 'rim-*.tar.gz'

    - name: Install rim
      run: |
        sudo tar xzf rim-*.tar.gz -C /usr/local

    - name: Install bats
      run: |
        sudo apt-get update && sudo apt-get install bats

    - name: Run tests
      run: |
        bats tests/test-linux.sh

  linux-arm:
    runs-on: [self-hosted, Linux, arm64]
    name: Linux-aaarch
    env:
      RUST_BACKTRACE: 1

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Build rim
      run: |
        docker system prune -f
        docker build -t rim:latest .
        docker rm quickrim 2>/dev/null || true
        docker run --name quickrim rim:latest ls out
        docker cp quickrim:out .
        ls out
        cp out/rim* .

    - name: Upload build as artifact
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: rim-linux-aarch64
        path: 'rim-*.tar.gz'

# TODO: run tests in Docker container

  macos:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
    env:
      RUST_BACKTRACE: 1

    strategy:
      fail-fast: false
    matrix:
      config:
        - { os: macOS-11    }
        - { os: macos-10.15 }

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Install rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rust.sh
        sh rust.sh -y

    - name: Build rim
      run: |
        make macos-unsigned-x86_64

    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: rim-${{ matrix.config.os }}
        path: 'rim-*.pkg'

    - name: Install rim
      run: |
        sudo installer -pkg rim-*.pkg -target /

    - name: Install bats
      run: brew install bats-core

    - name: Run tests
      run: |
        bats tests/test-macos.sh

  windows:
    runs-on: windows-latest
    name: Windows
    env:
      RUST_BACKTRACE: 1

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install make
      run: choco install make

    - name: Install curl
      run: choco install curl

    - run: |
        make win
      shell: bash

    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: rim-windows
        path: 'rim-*.exe'

    - name: Install rim
      run: |
        Start-Process .\rim-*.exe -ArgumentList "/verysilent /suppressmsgboxes" -Wait -NoNewWindow

    - name: Install bats
      run: |
        npm install -g bats

    - name: Run tests
      run: |
        bats tests/test-windows.sh
      shell: bash
