
name: Test

on:
  workflow_dispatch:
  push:
    branches: [ 'dev', 'main' ]
  schedule:
  - cron: '30 6 * * *'

jobs:
  linux:
    runs-on: ubuntu-18.04
    if: false
    name: Linux

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Build rim
      run: |
        docker build -o out .

  macos:
    runs-on: macos-11
    if: false
    name: macOS

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Install rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rust.sh
        sh rust.sh -y

    - name: Build rim
      run: |
        make macos-unsigned-x86_64

  windows:
    runs-on: windows-latest
    name: Windows

    steps:

    - name: find
      run: |
        find --help
      shell: bash

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install make
      run: choco install make

    - name: Install curl
      run: choco install curl

    - run: |
        make win
      shell: bash
