
name: Test

on:
  workflow_dispatch:
  push:
    branches: [ 'dev', 'main' ]
  schedule:
  - cron: '30 6 * * *'

jobs:

  linux:
    runs-on: ubuntu-18.04
    if: false
    name: Linux

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Build rim
      run: |
        docker build -t rim:latest .
        docker run --name quickrim rim:latest ls out
        docker cp quickrim:out .
        ls out
        cp out/rim* .

    - name: Upload build as artifact
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: rim-linux
        path: 'rim-*.tar.gz'

    - name: Install rim
      run: |
        sudo tar xzf rim-*.tar.gz -C /usr/local

    - name: Install bats
      run: |
        sudo apt-get update && sudo apt-get install bats

    - name: Run tests
      run: |
        bats tests/test-linux.sh

  macos:
    runs-on: macos-11
    if: false
    name: macOS

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Install rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rust.sh
        sh rust.sh -y

    - name: Build rim
      run: |
        make macos-unsigned-x86_64

    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: rim-macos
        path: 'rim-*.pkg'

    - name: Install rim
      run: |
        sudo installer -pkg rim-*.pkg -target /

    - name: Install bats
      run: brew install bats-core

    - name: Run tests
      run: |
        bats tests/test-macos.sh

  windows:
    runs-on: windows-latest
    name: Windows

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install make
      run: choco install make

    - name: Install curl
      run: choco install curl

    - run: |
        make win
      shell: bash

    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: rim-windows
        path: 'rim-*.exe'

    - name: Install rim
      run: |
        Start-Process .\rim-*.exe -ArgumentList "/verysilent /suppressmsgboxes" -Wait -NoNewWindow
        echo "C:\Program Files\rim" | Out-File -Append -FilePath $env:GITHUB_PATH

    - name: Install bats
      run: |
        npm install -g bats

    - name: test rim is in path
      run: |
        rim --help

    - name: rim with bash
      run: |
        rim --help
      shell: bash

    - name: Run tests
      run: |
        bats tests/test-windows.sh
      shell: bash
